baseURL = "https://yumeyumeji.com/"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true
languageCode = "ja"
title = "yumeji-official"
theme = "hugo-coder-main"

[languages]
  [languages.ja]
    languageName = "日本語"
    weight = 1

[params]
  favicon_32 = "images/favicon.png"
  keywords = "夢二, ギター, 音楽, 同人, VR, 東方, PHANOTOM, ばんぶーろまんす"
  colorScheme = "light"
  hideColorSchemeToggle = true
  description = "夢二の個人サイトです"
  customCSS = ["css/custom.css"]
  avatarURL = "images/icon.jpg"
  author = "Yumeji"
  #OGP画像を指定
  image = "images/ogp.jpg"

  [[params.social]]
    name = "X"
    url  = "https://x.com/Yumeji_122"

  [[params.social]]
    name = "YouTube"
    url  = "https://www.youtube.com/channel/UCklrdpcJIbHBUXY7rDpBPpA"

  [[params.social]]
    name = "foriio"
    url  = "https://www.foriio.com/yumeji"

  [[params.social]]
    name = "BOOTH"
    url  = "https://bamboormnc.booth.pm/"

[menu]
  [[menu.main]]
  identifier = "home"
  name = "HOME"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "about"
  name = "ABOUT"
  url = "/about/"
  weight = 2

  # [[menu.main]]
  # identifier = "discography"
  # name = "Discography"
  # url = "/discography/"
  # weight = 3

  [[menu.main]]
  identifier = "contact"
  name = "CONTACT"
  url = "/contact/"
  weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true